# Generated by Django 3.0.4 on 2020-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shortdescription', models.TextField(max_length=120)),
                ('description', models.TextField()),
                ('mainimg', models.TextField()),
                ('img1', models.TextField()),
                ('img2', models.TextField()),
                ('img3', models.TextField()),
                ('img4', models.TextField()),
                ('img5', models.TextField()),
                ('img6', models.TextField()),
                ('videp', models.TextField()),
            ],
        ),
    ]
